"""Label-permutation null for the held-out-unit protocol.

Chance is not always 0.5. Fold structure, class ratios and the model family all
shift where a meaningless result actually sits, so the baseline has to be
generated by this pipeline rather than assumed.

The permutation acts on the label vector alone. Features and grouping never
enter the function, so a permutation cannot corrupt them - which is the bug
that would silently turn this null into a meaningless one.
"""

from dataclasses import dataclass, field

import numpy as np
from joblib import Parallel, delayed

from nerveml.validation import SUBJECT_COLUMN, TARGET_COLUMN, build_grouped_scorer

ALPHA = 0.05


@dataclass
class PermutationResult:
    observed: float
    p_value: float
    null_mean: float
    null_std: float
    n_permutations: int
    null_scores: list = field(default_factory=list)

    def to_dict(self):
        return {
            "n_permutations": self.n_permutations,
            "observed_balanced_accuracy": round(self.observed, 4),
            "p_value": round(self.p_value, 4),
            "null_mean": round(self.null_mean, 4),
            "null_std": round(self.null_std, 4),
        }


def permute_labels_within_group(y, groups, rng):
    """Shuffle labels inside each group, leaving group membership alone.

    Each unit keeps its own label counts, so the null retains the per-unit
    class imbalance present in the real data. Shuffling globally would destroy
    that imbalance and produce a null that is easier to beat than the data,
    which reads as significance where none exists.
    """
    permuted = np.array(y, copy=True)
    for unit in np.unique(groups):
        rows = np.flatnonzero(groups == unit)
        permuted[rows] = rng.permutation(permuted[rows])
    return permuted


def permutation_test(
    df,
    feature_columns,
    group_column=SUBJECT_COLUMN,
    model=None,
    n_permutations=100,
    n_splits=5,
    seed=0,
    n_jobs=1,
):
    """Compare the observed grouped score against labels that mean nothing.

    n_jobs spreads the permutations over threads. The label vectors are drawn
    up front from a single seeded generator so the null distribution stays
    identical whatever the thread count.
    """
    scorer = build_grouped_scorer(
        df,
        feature_columns,
        group_column=group_column,
        model=model,
        n_splits=n_splits,
        seed=seed,
    )
    y = df[TARGET_COLUMN].to_numpy()
    groups = df[group_column].to_numpy()

    observed = scorer.score(y)

    rng = np.random.default_rng(seed)
    permuted_labels = [
        permute_labels_within_group(y, groups, rng) for _ in range(n_permutations)
    ]
    null_scores = Parallel(n_jobs=n_jobs, prefer="threads")(
        delayed(scorer.score)(labels) for labels in permuted_labels
    )

    # The +1 on both sides keeps p bounded away from zero: a finite number of
    # permutations cannot demonstrate an arbitrarily small p-value.
    n_at_least_as_good = sum(score >= observed for score in null_scores)
    p_value = (1 + n_at_least_as_good) / (1 + n_permutations)

    return PermutationResult(
        observed=float(observed),
        p_value=float(p_value),
        null_mean=float(np.mean(null_scores)),
        null_std=float(np.std(null_scores)),
        n_permutations=n_permutations,
        null_scores=[float(s) for s in null_scores],
    )
